/**
 * @fileOverview A Genkit flow for generating personalized practice questions based on a user's quiz performance.
 *
 * - intelligentReviewMode - A function that generates personalized practice questions.
 * - IntelligentReviewModeInput - The input type for the intelligentReviewMode function.
 * - IntelligentReviewModeOutput - The return type for the intelligentReviewMode function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

/**
 * Represents the input for the Intelligent Review Mode flow.
 * It includes topics where the user performed poorly and optionally, the text of questions answered incorrectly.
 */
const IntelligentReviewModeInputSchema = z.object({
  weakTopics: z.array(z.string()).describe("A list of topics where the user performed poorly in the quiz, e.g., 'Normas de Tránsito Generales', 'Mecánica y Seguridad Vial'. These topics will guide the generation of new questions."),
  incorrectQuestionTexts: z.array(z.string()).optional().describe("Optional: The text of the questions that the user answered incorrectly, to provide additional context for generating new questions."),
});
export type IntelligentReviewModeInput = z.infer<typeof IntelligentReviewModeInputSchema>;

/**
 * Represents a single personalized practice question generated by the AI.
 */
const PracticeQuestionSchema = z.object({
  questionText: z.string().describe("The text of the new practice question."),
  options: z.array(z.string()).describe("An array of possible answers for the question."),
  correctAnswer: z.string().describe("The correct answer among the options (should be one of the strings in the 'options' array)."),
  explanation: z.string().describe("A brief explanation for the correct answer, ideally citing the relevant Colombian traffic code or principle."),
});

/**
 * Represents the output of the Intelligent Review Mode flow.
 * It contains an array of personalized practice questions.
 */
const IntelligentReviewModeOutputSchema = z.object({
  personalizedQuestions: z.array(PracticeQuestionSchema).describe("An array of new, personalized practice questions focusing on the identified weak topics."),
});
export type IntelligentReviewModeOutput = z.infer<typeof IntelligentReviewModeOutputSchema>;

/**
 * Defines a prompt that instructs the AI to generate personalized practice questions.
 * It uses the identified weak topics and incorrect question texts as context.
 */
const intelligentReviewPrompt = ai.definePrompt({
  name: 'intelligentReviewPrompt',
  input: { schema: IntelligentReviewModeInputSchema },
  output: { schema: IntelligentReviewModeOutputSchema },
  prompt: `Eres un experto en el Código Nacional de Tránsito de Colombia y un tutor pedagógico.
El usuario ha completado un examen teórico de conducción y ha demostrado debilidades en los siguientes temas:

Temas débiles: {{#each weakTopics}} - {{{this}}}
{{/each}}

{{#if incorrectQuestionTexts}}
Para darte más contexto sobre los puntos específicos de confusión del usuario, aquí están algunas de las preguntas que respondió incorrectamente:
{{#each incorrectQuestionTexts}} - {{{this}}}
{{/each}}
{{/if}}

Genera 5 nuevas y distintas preguntas de práctica que se centren específicamente en estos temas débiles. Cada pregunta debe ser de opción múltiple con 4 opciones. Para cada pregunta, proporciona el texto de la pregunta, las 4 opciones de respuesta (como cadenas de texto), la respuesta correcta (una de las opciones proporcionadas) y una explicación concisa y clara de por qué esa es la respuesta correcta, haciendo referencia al Código Nacional de Tránsito de Colombia o principios de seguridad vial cuando sea posible.

Asegúrate de que las preguntas sean del estilo y dificultad de un examen teórico de conducción real en Colombia.
Proporciona tu respuesta en formato JSON, siguiendo estrictamente el esquema de salida.`,
});

/**
 * Defines the Genkit flow for generating personalized practice questions.
 * It takes weak topics and incorrect question texts as input and returns new practice questions.
 */
const intelligentReviewModeFlow = ai.defineFlow(
  {
    name: 'intelligentReviewModeFlow',
    inputSchema: IntelligentReviewModeInputSchema,
    outputSchema: IntelligentReviewModeOutputSchema,
  },
  async (input) => {
    const { output } = await intelligentReviewPrompt(input);
    return output!;
  }
);

/**
 * An exported wrapper function to call the intelligent review mode Genkit flow.
 * @param input - The input containing weak topics and optionally incorrect question texts.
 * @returns A promise that resolves to an object containing personalized practice questions.
 */
export async function intelligentReviewMode(input: IntelligentReviewModeInput): Promise<IntelligentReviewModeOutput> {
  return intelligentReviewModeFlow(input);
}
